version: '3.8'

services:
  meme-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arrogance-meme-creator
    volumes:
      - ./output:/app/output
      - ./.env:/app/.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - SERVICE_PORT=8000
      - SERVICE_HOST=0.0.0.0
      - LOG_LEVEL=info
      # Les autres variables d'environnement sont définies dans le fichier .env
    # Pour générer un mème avec un sujet spécifique
    # command: python src/generate_meme.py -s "Les politiciens" --telegram
    
    # Pour lancer l'API web (si implémentée)
    # command: python src/main.py 